# Generated by Django 3.2.6 on 2021-08-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses_passed',
            field=models.ManyToManyField(null=True, to='account.Course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_step',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
