# Generated by Django 3.2.6 on 2021-08-26 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210826_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses_passed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(max_length=10, null=True)),
                ('timezone', models.TextField(max_length=40, null=True)),
                ('telegram_id', models.IntegerField(null=True)),
                ('current_step', models.TextField(null=True)),
                ('courses_passed', models.ManyToManyField(null=True, to='account.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
