# Generated by Django 3.2.6 on 2021-08-27 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210827_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Answer',
            new_name='TestAnswer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answers',
            field=models.ManyToManyField(to='account.TestAnswer'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='correct_answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct', to='account.testanswer'),
        ),
    ]
