# Generated by Django 3.2.6 on 2021-08-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210827_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='testquestion',
            name='correct_answer',
            field=models.ManyToManyField(related_name='correct', to='account.TestAnswer'),
        ),
    ]
