# Generated by Django 3.2.6 on 2021-08-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210827_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='answers',
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='testquestion',
            name='correct_answer',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='TestAnswer',
        ),
    ]
