# Generated by Django 3.2.6 on 2021-08-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='answer_4',
        ),
        migrations.RemoveField(
            model_name='testquestion',
            name='answer_5',
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answers',
            field=models.ManyToManyField(to='account.TestAnswer'),
        ),
    ]
