# Generated by Django 3.2.6 on 2021-08-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210830_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestResults',
            new_name='TestResult',
        ),
    ]
