# Generated by Django 3.2.6 on 2021-09-02 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_testresults_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bot_token',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='CourseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('time', models.TimeField()),
                ('text', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='account.course')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_steps', to='account.survey')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_steps', to='account.test')),
            ],
        ),
    ]
