# Generated by Django 3.2.6 on 2021-09-03 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_testresults_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.TextField()),
                ('telegram_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('text', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('status', models.TextField(choices=[('CREATED', 'Открыто'), ('IN_WORK', 'В работе'), ('CLOSED', 'Завершено')], default='CREATED')),
                ('response', models.TextField(null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.bot')),
            ],
        ),
    ]
