# Generated by Django 3.2.6 on 2021-09-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_bot_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscode',
            options={'verbose_name': 'Код доступа', 'verbose_name_plural': 'Коды доступа'},
        ),
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='surveypossibleanswer',
            options={'verbose_name': 'Ответ на опрос', 'verbose_name_plural': 'Ответы на опросы'},
        ),
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={'verbose_name': 'Пункт опроса', 'verbose_name_plural': 'Пункты опросов'},
        ),
        migrations.AlterModelOptions(
            name='surveyuseranswer',
            options={'verbose_name': 'Пользовательский ответ на вопрос', 'verbose_name_plural': 'Пользовательские ответы на опросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='testactioncondition',
            options={'verbose_name': 'Условия действий тестов', 'verbose_name_plural': 'Условия действий тестов'},
        ),
        migrations.AlterModelOptions(
            name='testanswer',
            options={'verbose_name': 'Ответ для теста', 'verbose_name_plural': 'Ответы для теста'},
        ),
        migrations.AlterModelOptions(
            name='testmeaning',
            options={'verbose_name': 'Расшифровка теста', 'verbose_name_plural': 'Расшифровки тестов'},
        ),
        migrations.AlterModelOptions(
            name='testquestion',
            options={'verbose_name': 'Вопрос к тесту', 'verbose_name_plural': 'Вопросы к тесту'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты теста'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Билет поддержки', 'verbose_name_plural': 'Билеты поддержки'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AddField(
            model_name='bot',
            name='token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.TextField(choices=[('CREATED', 'Открыто'), ('IN_WORK', 'В работе'), ('CLOSED', 'Завершено')], default=('CREATED', 'Открыто')),
        ),
    ]
