# Generated by Django 3.2.6 on 2021-09-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20210907_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={'verbose_name': 'Вопрос опроса', 'verbose_name_plural': 'Вопросы опросов'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.TextField(choices=[('Открыто', 'Открыто'), ('В работе', 'В работе'), ('Завершено', 'Завершено')], default='Открыто'),
        ),
    ]
