# Generated by Django 3.2.6 on 2021-09-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210902_1354'),
        ('account', '0018_auto_20210907_1730'),
    ]

    operations = [
    ]
