# Generated by Django 3.2.6 on 2021-09-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_merge_0016_auto_20210902_1354_0018_auto_20210907_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='bot_token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='TrainingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('time', models.TimeField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('text', models.TextField(blank=True, null=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='account.training')),
            ],
        ),
    ]
