# Generated by Django 3.2.6 on 2021-09-09 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_course_bot_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='bot_token',
        ),
        migrations.AddField(
            model_name='course',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.bot'),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.TextField(default='', max_length=100),
        ),
    ]
