# Generated by Django 3.2.6 on 2021-09-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20210909_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='telegram_id',
        ),
    ]
