# Generated by Django 3.2.6 on 2021-09-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_bot_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='current_port',
            field=models.IntegerField(null=True),
        ),
    ]
