# Generated by Django 3.2.6 on 2021-09-14 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20210914_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='possible_answers',
        ),
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveypossibleanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.surveyquestion'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.survey'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_1_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_2_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_3_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_4_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_5_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answer_6_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TestAnswer',
        ),
    ]
