# Generated by Django 3.2.6 on 2021-09-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20210914_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer_1_weight',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer_2_weight',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer_3_weight',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer_4_weight',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer_5_weight',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer_6_weight',
        ),
    ]
