# Generated by Django 3.2.6 on 2021-09-14 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20210914_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='testevent',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.test'),
        ),
        migrations.AlterField(
            model_name='client',
            name='current_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_course', to='account.course'),
        ),
    ]
