# Generated by Django 3.2.6 on 2021-09-14 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20210914_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testevent',
            name='meaning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testevent',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.training'),
        ),
    ]
