# Generated by Django 3.2.6 on 2021-09-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20210914_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='test',
            name='trainings',
        ),
        migrations.DeleteModel(
            name='TestMeaning',
        ),
    ]
