# Generated by Django 3.2.6 on 2021-09-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20210914_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='course',
        ),
    ]
