# Generated by Django 3.2.6 on 2021-09-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_remove_trainer_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingstep',
            options={'ordering': ['id'], 'verbose_name': 'Шаг тренировки', 'verbose_name_plural': 'Шаги тренировок'},
        ),
        migrations.RemoveField(
            model_name='training',
            name='threshold',
        ),
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
