# Generated by Django 3.2.6 on 2021-09-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_auto_20210916_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='handle',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
