# Generated by Django 3.2.6 on 2021-09-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_auto_20210918_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
