# Generated by Django 3.2.6 on 2021-09-19 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_alter_textmessage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='response',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='text',
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('OPERATOR', 'Ответ оператора'), ('USER', 'Сообщение пользователя')], default='OPERATOR', max_length=40)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ticket')),
            ],
        ),
    ]
