# Generated by Django 3.2.6 on 2021-09-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_alter_testevent_training'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['id'], 'verbose_name': 'Сообщение билета поддержки'},
        ),
    ]
