# Generated by Django 3.2.6 on 2021-09-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_auto_20210920_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_courses', to='account.coursecategory'),
        ),
    ]
