# Generated by Django 3.2.6 on 2021-09-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_auto_20210927_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestep',
            name='text_message_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='bot_problem_type',
            field=models.TextField(choices=[('Не удаёется активировать', 'Не удаёется активировать'), ('Не присылает уведомления', 'Не присылает уведомления'), ('Задваиваются сообщения', 'Задваиваются сообщения'), ('Другая проблема', 'Другая проблема')], null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='problem_type',
            field=models.TextField(choices=[('Технические проблемы с чат ботом', 'Технические проблемы с чат ботом'), ('Вопрос по продукту', 'Вопрос по продукту'), ('Вопрос по курсу или тренировкам', 'Вопрос по курсу или тренировкам')], null=True),
        ),
        migrations.AlterField(
            model_name='coursestep',
            name='text_message',
            field=models.TextField(blank=True, null=True, verbose_name='course_steps'),
        ),
        migrations.DeleteModel(
            name='TextMessage',
        ),
    ]
