# Generated by Django 3.2.6 on 2021-09-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_auto_20210927_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='testevent',
            name='meaning_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
