# Generated by Django 3.2.6 on 2021-09-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_auto_20210927_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='bot',
        ),
    ]
