# Generated by Django 3.2.6 on 2021-09-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_remove_ticket_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestep',
            name='text_message_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
