# Generated by Django 3.2.6 on 2021-09-30 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_coursestep_text_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='image',
        ),
        migrations.CreateModel(
            name='TestQuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='account.testquestion')),
            ],
        ),
    ]
