# Generated by Django 3.2.6 on 2021-09-30 17:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_auto_20210930_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer_4',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer_5',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answer_6',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
