# Generated by Django 3.2.6 on 2021-10-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_auto_20210930_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Обращение в службу поддержки', 'verbose_name_plural': 'Обращения в службу поддержки'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['id'], 'verbose_name': 'Сообщение'},
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='answers',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='answer_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='answer_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='answer_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='answer_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='answer_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='answer_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
