# Generated by Django 3.2.6 on 2021-10-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_auto_20211001_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='TestQuestionImage',
        ),
    ]
