# Generated by Django 3.2.6 on 2021-10-08 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_auto_20211008_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestep',
            name='text',
        ),
        migrations.AddField(
            model_name='textmessage',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='account.coursestep'),
        ),
    ]
