# Generated by Django 3.2.6 on 2021-10-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_auto_20211008_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmessage',
            name='step',
        ),
        migrations.AddField(
            model_name='coursestep',
            name='text_message',
            field=models.TextField(blank=True, null=True, verbose_name='course_steps'),
        ),
        migrations.AddField(
            model_name='coursestep',
            name='text_message_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coursestep',
            name='text_message_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
