# Generated by Django 3.2.6 on 2021-10-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_client_is_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
