# Generated by Django 3.2.6 on 2021-10-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='current_course',
        ),
        migrations.RemoveField(
            model_name='client',
            name='current_step',
        ),
        migrations.AddField(
            model_name='client',
            name='current_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='current_courses', to='account.Course'),
        ),
        migrations.AddField(
            model_name='client',
            name='current_steps',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
